import React from 'react'

export function Privacypolicy() {
  return (
    <div className='pt-28'>
        
        Privacy Policy
Last Updated March 07, 2023
This privacy policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use your personal data to provide and improve the service. By using the service, You agree to the collection and use of information in accordance with this privacy policy. This privacy policy has been created with the help of the

Defintion
For the purposes of this privacy policy:

An account is a unique account created for you to access our service or parts of our service.
Affiliate means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority
Application refers to Froker, the software program provided by the company.
Company (referred to as either "the Company", "We", "Us" or "Our" in this agreement) refers to Froker.
Country refers to: Karnataka, India
Device means any device that can access the service such as a computer, a cellphone or a digital tablet.
Personal Data is any information that relates to an identified or identifiable individual.
Service refers to the application.
A service provider is any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the service, to provide the service on behalf of the company, to perform services related to the service, or to assist the company in analysing how the service is used.
Usage data refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).
You means the individual accessing or using the service, or the company or other legal entity on behalf of which such individual is accessing or using the service, as applicable.
Collecting and Using Your
Personal Data
Personal Data:
While using our service, We may ask you to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to Usage Data

Usage Data
Usage Data is collected automatically when using the service.
Usage Data may include information such as your device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.When you access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
Use of Your Personal Data
The company may use personal data for the following purposes:
To provide and maintain our service, including to monitor the usage of our service.
To manage Your account:to manage your registration as a user of the service. The personal data you provide can give you access to different functionalities of the service that are available to you as a registered user.
For the performance of a contract:the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or of any other contract with us through the service.
To contact You:To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.
To provide you with news, special offers, and general information about other goods, services, and events that we offer that are similar to those that you have already purchased or inquired about, unless you have opted not to receive such information.
To manage Your requests:To attend and manage Your requests to us.
For business transfers:we may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganisation, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal data held by us about our service users is among the assets transferred.
For other purposes:We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our service, products, services, marketing, and your experience.
We may share Your personal information in the following situations:
With Service Providers:We may share your personal information with service providers to monitor and analyse the use of our service and to contact you.
For business transfers:We may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.
With Affiliates:We may share your information with our affiliates, in which case we will require those affiliates to honour this privacy olicy. Affiliates include our parent company and any other subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.
With business partners:We may share your information with our business partners to offer you certain products, services, or promotions.
With other users:When you share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
With Your consent:We may disclose your personal information for any other purpose.
Retention of Your Personal Data
The company will retain your personal data only for as long as is necessary for the purposes set out in this privacy policy. We will retain and use your personal data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
The company will also retain usage data for internal analysis purposes. Usage data is generally retained for a shorter period of time, except when this data is used to strengthen the security or improve the functionality of our service, or we are legally obligated to retain this data for longer time periods.

Transfer of Your Personal Data
The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.

Delete of Your Personal Data
You have the right to delete or request that we assist in deleting the personal data that we have collected about you. Our service may give you the ability to delete certain information about you from within the service. You may update, amend, or delete your information at any time by signing in to your account, if you have one, and visiting the account settings section that allows you to manage your personal information. You may also contact us to request access to, correct, or delete any personal information that you have provided to us.
Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.

Disclousure of Your Personal Data
Business Transactions
If the company is involved in a merger, acquisition, or asset sale, your personal data may be transferred. We will provide notice before your personal data is transferred and becomes subject to a different privacy policy.
Law Enforcement
Under certain circumstances, the company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).
Other Legal Requirements
The company may disclose your personal data in the good faith belief that such action is necessary to:
Comply with a legal obligation
Protect and defend the rights or property of the company.
Prevent or investigate possible wrongdoing in connection with the service.
Protect the personal safety of Users of the Service or the public.
Protect against legal liability.
Security of Your Personal Data
The security of your personal data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.

Children's Privacy
Our service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we will take steps to remove that information from our servers.
If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.

Links to Other Websites
Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

Changes to this Privacy Policy
We may update our privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page. We will let you know via email and/or a prominent notice on our service prior to the change becoming effective and update the "Last updated" date at the top of this privacy policy.
You are advised to review this privacy policy periodically for any changes. Changes to this privacy policy are effective when they are posted on this page.

Delivery, Payment, Refund and Return Policy
Guaranteed Delivery:You'll receive your ordered item within 4 hours from order placement.
Delivery Confirmation:We'll provide confirmation once your order is successfully delivered.
Timely Updates: Stay informed with real-time updates on your order's status and expected delivery time.
Source of Refund:Refunds will be credited to the same account used for the transaction.
Refund Processing Time:Refunds will be credited to the same account used for the transaction.
Item Issues:In case of any issues with the delivered item, refunds will be processed within 3 business days after our team's approval.
No Returns:We regret to inform you that we do not accept returns for any products purchased from our store.
Quality Assurance:We are committed to providing you with high-quality products. If you receive a damaged or defective item, please contact our customer service within 1 hours of receiving the order, along with photographic evidence of the issue. We will assess the situation and provide a resolution accordingly.
Order Cancellation:Orders cannot be cancelled or modified once they have been placed and payment has been processed.
    </div>
  )
}

